########################################
# admin_login
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_login", "params": [
"admin@localhost",
"wrong password"
]}


########################################
# admin_login
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_login", "params": [
"admin@localhost",
"fAP7IcyW"
]}


########################################
# admin_set_notification
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_set_notification", "params": [
"HywGMUT0oMTzbAAC",
"new notification test"
]}


########################################
# admin_settings
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_settings", "params": [
"wlfUJEf0jwzNjvgV"
]}


########################################
# admin_settings
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_settings", "params": [
"wlfUJEf0jwzNjvgV",
"40"
]}


########################################
# admin_approve_node
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_approve_node", "params": [
"fi9GCvAeIIldzxJM",
"0x000000000000000000000000000000000000000000000000000000000000000003"
]}


########################################
# admin_revoke_node
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_revoke_node", "params": [
"fi9GCvAeIIldzxJM",
"0x000000000000000000000000000000000000000000000000000000000000000003"
]}


########################################
# admin_logout
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_logout", "params": [
"wlfUJEf0jwzNjvgV"
]}


###

