########################################
# admin_login
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_login", "params": [
"admin@localhost",
"wrong password"
]}


########################################
# admin_login
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_login", "params": [
"admin@localhost",
"SA2tyE1s"
]}


########################################
# admin_set_notification
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_set_notification", "params": [
"XdqwsWXugME2e4tz",
"Warning: This is a demo pool with fake nodes for testing purpose only"
]}


########################################
# admin_settings
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_settings", "params": [
"wlfUJEf0jwzNjvgV"
]}


########################################
# admin_settings
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_settings", "params": [
"wlfUJEf0jwzNjvgV",
"40"
]}


########################################
# admin_approve_node
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_approve_node", "params": [
"fi9GCvAeIIldzxJM",
"0x000000000000000000000000000000000000000000000000000000000000000003"
]}


########################################
# admin_revoke_node
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_revoke_node", "params": [
"fi9GCvAeIIldzxJM",
"0x000000000000000000000000000000000000000000000000000000000000000003"
]}


########################################
# admin_logout
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_logout", "params": [
"wlfUJEf0jwzNjvgV"
]}


########################################
# admin_list_miners
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_list_miners", "params": [
"ANcMPkENKiUjfBQ0",
0,
10
]}


########################################
# admin_list_nodes
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "admin_list_nodes", "params": [
"ANcMPkENKiUjfBQ0",
0,
2
]}


########################################
# admin_rewards
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

# latest block
{"id": 1, "jsonrpc": "2.0", "method": "admin_rewards", "params": [
"agweXIPevvzQUbLV",
null
]}


########################################
# admin_rewards
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

# blocks 1 to 10
{"id": 1, "jsonrpc": "2.0", "method": "admin_rewards", "params": [
"agweXIPevvzQUbLV",
"1-10"
]}


########################################
# admin_rewards
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

# blocks 20 to 10, add block 1
{"id": 1, "jsonrpc": "2.0", "method": "admin_rewards", "params": [
"agweXIPevvzQUbLV",
"20-10, 1"
]}
###

