########################################
# zil_requestWork
# DATA, 33 Bytes - the Zilliqa node PubKey
# DATA, 32 Bytes - current block header pow-hash
# Block Num, 8 Bytes - hex string of block number, to generate the seed hash used for the DAG.
# DATA, 32 Bytes - the boundary condition ("target"), 2^256 / difficulty.
# Mining Time, 4 Bytes - hex string of the mining time in seconds.
# DATA, 64 Bytes - the signature of the message
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "zil_requestWork", "params": [
 "0x02a349fa10f0e6a614a38d6033588a422357f2c60af2eebae15d06498df8af0b05",
 "0x372eca2454ead349c3df0ab5d00b0b706b23e49d469387db91811cee0358fc6d",
 "0x0000000000000003",
 "0x0007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
 "0x00000080",
 "0xc328480a5ca5785507a98a860f92a75d94a7f751aa230e023a50d3163212f8f5a1f23ff13ba6ee006cf0dc4cb000ab83f2be61174c4cbcd6bf9c7c999aa3ce61"
]}

########################################
# zil_checkWorkStatus
# DATA, 33 Bytes - the Zilliqa node PubKey
# DATA, 32 Bytes - current block header pow-hash
# DATA, 32 Bytes - the boundary condition ("target")
# DATA, 64 Bytes - the signature of the message
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "zil_checkWorkStatus", "params": [
 "0x02a349fa10f0e6a614a38d6033588a422357f2c60af2eebae15d06498df8af0b05",
 "0x372eca2454ead349c3df0ab5d00b0b706b23e49d469387db91811cee0358fc6d",
 "0x0007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
 "0x15ed63353ac5548814b7140e588a70eab3d94e620adfa273f4910e23475c76c068674b9741ce991ac3ec71754cf520a82835cc662d7199629ca128e8b437a86f"
]}


########################################
# zil_verifyResult
# DATA, 33 Bytes - the Zilliqa node PubKey
# Verified, 1 Bytes - the PoW verify pass or fail
# DATA, 32 Bytes - The header's pow-hash (256 bits)
# DATA, 32 Bytes - the boundary condition ("target")
# DATA, 64 Bytes - the signature of the message
POST http://localhost:4202/api
Accept: application/json
Cache-Control: no-cache

{"id": 1, "jsonrpc": "2.0", "method": "zil_verifyResult", "params": [
 "0x02a349fa10f0e6a614a38d6033588a422357f2c60af2eebae15d06498df8af0b05",
 "0x01",
 "0x372eca2454ead349c3df0ab5d00b0b706b23e49d469387db91811cee0358fc6d",
 "0x0007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
 "0x140b22e7bee34bc063fa9ccc25d2d3a5007efea3d38333e94ad396be3f76a7f5b34f48a44c8991cf85eed4ae7b9d0e15dc8460bdd9ecf6274a3854b300e20417"
]}

########################################
